name: Deploy to Coral Dev Board (Test)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and Run Script
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run Application in Background
        run: |
          echo "Stopping previous instances of the script..."
          # pkill 명령어로 이전에 실행중이던 스크립트 프로세스를 찾아 종료
          # "|| true"는 해당 프로세스가 없어서 에러가 나도 워크플로우가 멈추지 않게 함
          pkill -f lcd_http_test.py || true

          echo "Starting new script in the background..."
          # nohup: 터미널 세션이 끊겨도 프로세스가 계속 실행되게 함
          # &: 프로세스를 백그라운드에서 실행
          nohup python3 lcd_http_test.py &
